application:
    build: code
    volumes:
        - ./wescape:/var/www/symfony
        - ./logs/symfony:/var/www/symfony/app/logs
    tty: true

db:
    image: mysql
    ports:
        - wescape.dev:3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wescape

testing_db:
    image: mysql
    ports:
        - 13306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root_test
        MYSQL_DATABASE: wescape_test

php:
    # build: php-fpm
    image: ilariopierbattista/wescape-api:php-fpm
    ports:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db:wescape.db.service
        - testing_db:wescape.db.service

nginx:
    # build: nginx
    image: ilariopierbattista/wescape-api:nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx

# Ne facciamo volentieri a meno
#elk:
#    image: willdurand/elk
#    ports:
#        - 81:80
#    volumes:
#        - ./elk/logstash:/etc/logstash
#        - ./elk/logstash/patterns:/opt/logstash/patterns
#    volumes_from:
#        - application
#        - php
#        - nginx
