wescape_api_Node:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\NodeController
  name_prefix: api_1_

wescape_api_Edge:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\EdgeController
  name_prefix: api_1_

wescape_api_User:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\UserController
  name_prefix: api_1_

wescape_api_Position:
  type:   rest
  parent: wescape_api_User
  resource: Wescape\ApiBundle\Controller\PositionController
  name_prefix: api_1_

wescape_api_Emergency:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\EmergencyController
  name_prefix: api_1_