wescape_api_Node:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\NodeController
  name_prefix: api_1_

wescape_api_Edge:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\EdgeController
  name_prefix: api_1_