wescape_api_Node:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\NodeRESTController
  name_prefix: api_1_

wescape_api_Edge:
  type: rest
  prefix: /v1
  resource: Wescape\ApiBundle\Controller\EdgeRESTController
  name_prefix: api_1_
