services:
  exists.client.validator:
    class: Wescape\CoreBundle\Validator\Constraint\ClientExistsValidator
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: validator.constraint_validator , alias: exists.client.validator }

  core.password_reset:
    class: Wescape\CoreBundle\Service\PasswordResetService
    arguments:
      - "@fos_user.user_manager"
      - "@mailer"
      - "@twig"

  core.user_voter:
    class: Wescape\CoreBundle\Security\UserVoter
    tags:
      - { name: security.voter }
    public: false
    arguments: [ '@security.access.decision_manager' ]

  core.position_voter:
    class: Wescape\CoreBundle\Security\PositionVoter
    tags:
      - { name: security.voter }
    public: false
    arguments: [ "@security.access.decision_manager" ]