services:
  exists.client.validator:
    class: Wescape\CoreBundle\Validator\Constraint\ClientExistsValidator
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: validator.constraint_validator , alias: exists.client.validator }