imports:
    # framework, twig, doctrine, swiftmailer, fos_user
    - { resource: general.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    # fos_rest, nelmio_cors, nelmio_api_doc
    - { resource: restful.yml }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
    - { resource: "@BackendBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: it