# FOSRestBundle configuration
fos_rest:
  routing_loader:
    default_format: json
  param_fetcher_listener: true
  body_listener: true
  #disable_csrf_role: ROLE_USER
  body_converter:
    enabled: true
  view:
    formats:
      json: true
    view_response_listener: force
    # Questa voce non sarà supportata prima della versione 2.0 del bundle
    # versioning: true

nelmio_api_doc: ~

nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['*']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
      max_age: 3600