# FOSRestBundle configuration
fos_rest:
  routing_loader:
    default_format: json
  param_fetcher_listener: true
  body_listener: true
  #disable_csrf_role: ROLE_USER
  body_converter:
    enabled: true
  view:
    formats:
      json: true
    view_response_listener: force
    # Questa voce non sarà supportata prima della versione 2.0 del bundle
    # versioning: true

nelmio_api_doc: ~

nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['*']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
      max_age: 3600

fos_oauth_server:
  db_driver:           orm
  client_class:        Wescape\CoreBundle\Entity\Client
  access_token_class:  Wescape\CoreBundle\Entity\AccessToken
  refresh_token_class: Wescape\CoreBundle\Entity\RefreshToken
  auth_code_class:     Wescape\CoreBundle\Entity\AuthCode
  service:
    user_provider: fos_user.user_provider.username_email
