static:
    resource: "@StaticBundle/Controller/"
    type:     annotation
    prefix:   /static

api:
    type: rest
    resource: "@ApiBundle/Resources/config/routes.yml"
    prefix:   /api
    defaults: {_format: json} # Format default
    # Il versionamento delle API è hardcoded per il momento
    # Il FOSRestBundle supporterà il versioning dalla versione 2.0,
    # aggiornare quando uscirà dalla beta
    # prefix: /api/{version}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"